/**
 * @file dynamic-nutrition-plan.entity.js
 * @description Domain entity for a compensatory nutrition plan generated by the
 * backend from a plot's phenological-risk alert and monitoring indicators.
 * Mirrors the platform `DynamicNutritionPlanResource` contract.
 */

/**
 * @typedef {'Recommended'|'Optional'} NutritionInputStatus
 * @typedef {'Pending'|'Certified'} CertificationStatus
 */

/**
 * @class DynamicNutritionPlan
 */
export class DynamicNutritionPlan {
    /**
     * @param {Object} params
     * @param {number|null} [params.id=null]
     * @param {number|null} [params.userId=null]
     * @param {number|null} [params.plotId=null]
     * @param {NutritionInputStatus} [params.status='Recommended']
     * @param {Array<Object>} [params.inputs=[]]
     * @param {{startDate:string,endDate:string}|null} [params.applicationWindow=null]
     * @param {Object|null} [params.rationale=null]
     * @param {string} [params.generatedDate='']
     * @param {CertificationStatus} [params.certificationStatus='Pending']
     * @param {Object|null} [params.application=null]
     */
    constructor({
                    id = null,
                    userId = null,
                    plotId = null,
                    status = 'Recommended',
                    inputs = [],
                    applicationWindow = null,
                    rationale = null,
                    generatedDate = '',
                    certificationStatus = 'Pending',
                    application = null
                } = {}) {
        this.id = id;
        this.userId = userId;
        this.plotId = plotId;
        this.status = status;
        this.inputs = inputs;
        this.applicationWindow = applicationWindow;
        this.rationale = rationale;
        this.generatedDate = generatedDate;
        this.certificationStatus = certificationStatus;
        this.application = application;
    }

    /** @returns {string} Human plan code, e.g. "DN-042". */
    get planCode() {
        return `DN-${String(this.id ?? 0).padStart(3, '0')}`;
    }

    /** @returns {boolean} Whether the plan's field application is certified. */
    get isCertified() {
        return this.certificationStatus === 'Certified' || this.application !== null;
    }

    /** @returns {string[]} Recommended (non-optional) input names, for the Certify form. */
    get recommendedInputNames() {
        return this.inputs.filter((input) => input.status === 'Recommended').map((input) => input.name);
    }
}
